let mock = [
    {"name":"Agron Kabashi",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Lund",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },  {"name":"Agron Kabashi",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Stockholm",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },  {"name":"Agron Kabashi",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Atlanta",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },
    {"name":"Agron Kabashi",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Venice",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },
    {"name":"Sofia Olin",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"NYC",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },
    {"name":"Jon Miren",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Malmo",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    },
    {"name":"Leo Aresti",
        "email":"agron.kabashi@tretton37.com",
        "phoneNumber":"+46725133736",
        "office":"Calcutta",
        "manager":"lotta.wennolf@tretton37.com",
        "orgUnit":"/Employees",
        "mainText":"long as description",
        "gitHub":"AgronKabashi",
        "twitter":"_agronkabashi",
        "stackOverflow":null,
        "linkedIn":"/pub/agron-kabashi/54/6a8/4a6",
        "imagePortraitUrl":"https://i.1337co.de/profile/agron-kabashi",
        "imageWallOfLeetUrl":"https://i.1337co.de/wallofleet/agron-kabashi",
        "highlighted":false,
        "published":true
    }
]

export default mock;